# Generated by Django 5.1.5 on 2025-01-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_text', models.CharField(default='1', max_length=200)),
                ('day_text', models.CharField(max_length=200)),
                ('money_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_text', models.IntegerField(default=1)),
                ('active_text', models.BooleanField(default=True)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.money')),
            ],
        ),
    ]
